language: node_js
node_js:
  - "4.1"
before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
script: node_modules/karma/bin/karma start karma.coverage.js --single-run
after_script:
  - npm run generatetraviscoverage
  - "cat ./coverage/lcov-report/lcov | ./node_modules/coveralls/bin/coveralls.js"