language: node_js
node_js:
  - "5"
before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
install: 
  - npm install @angular/common@2.0.0-rc.6
  - npm install @angular/compiler@2.0.0-rc.6
  - npm install @angular/core@2.0.0-rc.6
  - npm install @angular/platform-browser@2.0.0-rc.6
  - npm install @angular/platform-browser-dynamic@2.0.0-rc.6
  - npm install rxjs@5.0.0-beta.11
script:
  - npm run build
  - npm run coverage
after_script:
  - npm run generatetraviscoverage
  - "cat ./coverage/lcov-report/lcov | ./node_modules/coveralls/bin/coveralls.js"